#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         0  # Grosor de los bordes
#bspc config focused_border_color "#4c46cd"  # Color azul para la ventana enfocada
#bspc config normal_border_color  "#cd4646"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^1' follow=on focus=on
#bspc rule -a Chromium desktop='^1' follow=on focus=on
bspc rule -a Brave-browser desktop='^1' follow=on focus=on
bspc rule -a kitty desktop='^2' follow=on focus=on
bspc rule -a lxterminal desktop='^2' follow=on focus=on
bspc rule -a VSCodium desktop='^3' follow=on focus=on
bspc rule -a Eclipse desktop='^3' follow=on focus=on
bspc rule -a jetbrains-idea-ce desktop='^3' follow=on focus=on
bspc rule -a sublime_text desktop='^3' follow=on focus=on
bspc rule -a rars-Launch desktop='^3' follow=on focus=on
bspc rule -a gns3 desktop='^4' follow=on focus=on
bspc rule -a GNS3 desktop='^4' follow=on focus=on
# bspc rule -a Vmware desktop='^4' follow=on focus=on
# bspc rule -a Virt-manager desktop='^4' follow=on focus=on
bspc rule -a cutter desktop='^5' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar bar &
#picom --config $HOME/.config/picom/picom.conf &
# picom -b &
# exec_always --no-startup-id picom -b
feh --bg-fill $HOME/Documents/wallpapers/astro-naught.png &

#eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets)
#export SSH_AUTH_SOCK
